/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_BUT.h"
#include "Pin_BUT_aliases.h"
#include "Clock_1.h"
#include "PWM_1.h"
#include "Pin_LED.h"
#include "Pin_LED_aliases.h"
#include "Pin_B_DPAD_R.h"
#include "Pin_B_DPAD_R_aliases.h"
#include "Pin_B_DPAD_L.h"
#include "Pin_B_DPAD_L_aliases.h"
#include "Pin_B_DPAD_U.h"
#include "Pin_B_DPAD_U_aliases.h"
#include "Pin_B_DPAD_D.h"
#include "Pin_B_DPAD_D_aliases.h"
#include "Pin_B_R_TRIG.h"
#include "Pin_B_R_TRIG_aliases.h"
#include "Pin_B_L_TRIG.h"
#include "Pin_B_L_TRIG_aliases.h"
#include "Pin_B_MENU.h"
#include "Pin_B_MENU_aliases.h"
#include "Pin_B_SELECT.h"
#include "Pin_B_SELECT_aliases.h"
#include "Pin_B_START.h"
#include "Pin_B_START_aliases.h"
#include "Pin_B_Y.h"
#include "Pin_B_Y_aliases.h"
#include "Pin_B_X.h"
#include "Pin_B_X_aliases.h"
#include "Pin_B_B.h"
#include "Pin_B_B_aliases.h"
#include "Pin_B_A.h"
#include "Pin_B_A_aliases.h"
#include "Pin_L_TRIG.h"
#include "Pin_L_TRIG_aliases.h"
#include "Pin_R_TRIG.h"
#include "Pin_R_TRIG_aliases.h"
#include "Pin_J1_AX.h"
#include "Pin_J1_AX_aliases.h"
#include "Pin_J1_AY.h"
#include "Pin_J1_AY_aliases.h"
#include "Pin_J0_AY.h"
#include "Pin_J0_AY_aliases.h"
#include "Pin_J0_AX.h"
#include "Pin_J0_AX_aliases.h"
#include "ADC_JOY.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "ADC_JOY_IRQ.h"
#include "ADC_JOY_intClock.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

